highlighter: pygments
markdown: rdiscount
rdiscount:
extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
gems:
  - jekyll-seo-tag
port: 3000
safe: true


url: https://amalrkrishna.github.io/
baseurl: https://amalrkrishna.github.io/
title: Amal R Krishna
author: Amal Krishna R
description: Webpage of Amal R Krishna
avatar: profile.png
name: Amal R Krishna
email: amalrk@bu.edu
email_full: amalrk@bu.edu
website: GitHub site
website_full: amalrkrishna.github.io
github: amalrkrishna # username
twitter: amalrkrishna94
linkedin: amalrkrishna
google_analytics: UA-78468673-1
quora: Amal-R-Krishna
hackerrank: amalrkrishna 
facebook: Ak.Grandiose
#tel: 
#tel_full: 
#google_maps: 
#address: 
postcode: 02134
city: Boston
country: United States

# needed for travis-ci build
exclude: [vendor]

theme: jekyll-theme-cayman